language: ruby

sudo: false

cache:
  - bundler

rvm: 2.4.1

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

addons:
  apt:
    packages:
      - aspell
      - aspell-en

before_install:
  # Install spellchecker.
  - npm install -g orta/node-markdown-spellcheck
  
  # Echo for Danger.
  - echo $TRAVIS_COMMIT_RANGE

  # Copy proselint settings to home.
  - cp .proselintrc ~/

script:
  - bundle exec rake build:test
  - bundle exec danger
